### ISSUE TITLE
[Bug]: Panic error at parseSearchResult func when query output FieldTypeArray type fields

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus-sdk-go#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- milvus image: v2.3.2
- go-branch: master

- Test steps:
1. create collection with all type fields (includes array field with all element type)
2. insert data and flush
3. create index and load
4. query with expr "int64 == 0" and output "*" fields, gets panic error:
```
--- FAIL: TestOutputAllFields (9.63s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9d22bd]

goroutine 6 [running]:
testing.tRunner.func1.2({0xb19820, 0x11b2140})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0xb19820, 0x11b2140})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/milvus-io/milvus-sdk-go/v2/entity.parseArrayData({0xc012d92e80, 0xa}, 0xc012d92d68?)
	/home/zong/zong/go-projects/milvus-sdk-go/entity/columns.go:334 +0x9bd
github.com/milvus-io/milvus-sdk-go/v2/entity.FieldDataColumn(0xc012df3680, 0x0, 0xffffffffffffffff)
	/home/zong/zong/go-projects/milvus-sdk-go/entity/columns.go:247 +0xf9a
github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).parseSearchResult(0xc000046ba0?, 0x0?, {0xc012d85780?, 0x0?, 0x0?}, {0xc0001dab00, 0x12, 0xc00009c0a0?}, 0xc013115ac8?, 0x0, ...)
	/home/zong/zong/go-projects/milvus-sdk-go/client/data.go:106 +0x157
github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).Query(0xc0000888c0, {0xd09ed0, 0xc000046ba0}, {0xc000430d10, 0x4}, {0x11fcf10, 0x0, 0x0}, {0xc012d92cb0, 0xa}, ...)
	/home/zong/zong/go-projects/milvus-sdk-go/client/data.go:289 +0x665
github.com/milvus-io/milvus-sdk-go/v2/test/base.(*MilvusClient).Query(0xc0004debe0, {0xd09ed0?, 0xc000046ba0}, {0xc000430d10, 0x4}, {0x11fcf10, 0x0, 0x0}, {0xc012d92cb0, 0xa}, ...)
	/home/zong/zong/go-projects/milvus-sdk-go/test/base/milvus_client.go:431 +0x366
github.com/milvus-io/milvus-sdk-go/v2/test/testcases.TestOutputAllFields(0x0?)
	/home/zong/zong/go-projects/milvus-sdk-go/test/testcases/query_test.go:430 +0x874
testing.tRunner(0xc00035cb60, 0xc48990)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

- Test case:
```
func TestOutputAllFields(t *testing.T) {
	ctx := createContext(t, time.Second*common.DefaultTimeout)
	// connect
	mc := createMilvusClient(ctx, t)

	// create collection
	var capacity int64 = common.TestCapacity
	cp := CollectionParams{CollectionFieldsType: AllFields, AutoID: false, EnableDynamicField: true,
		ShardsNum: common.DefaultShards, Dim: common.DefaultDim, MaxCapacity: capacity}
	collName := createCollection(ctx, t, mc, cp)

	// prepare and insert data
	dp := DataParams{CollectionName: collName, PartitionName: "", CollectionFieldsType: AllFields,
		start: 0, nb: common.DefaultNb, dim: common.DefaultDim, EnableDynamicField: true, WithRows: false}
	_, _ = insertData(ctx, t, mc, dp, common.WithArrayCapacity(capacity))

	// flush and check row count
	errFlush := mc.Flush(ctx, collName, false)
	common.CheckErr(t, errFlush, true)

	idx, _ := entity.NewIndexHNSW(entity.L2, 8, 96)
	_ = mc.CreateIndex(ctx, collName, common.DefaultFloatVecFieldName, idx, false)

	// Load collection
	errLoad := mc.LoadCollection(ctx, collName, false)
	common.CheckErr(t, errLoad, true)

	// query with non-primary field
	var start int = 0
	var nb int = 1
	data := []entity.Column{
		common.GenColumnData(start, nb, entity.FieldTypeInt64, "int64"),
		common.GenColumnData(start, nb, entity.FieldTypeBool, "bool"),
		common.GenColumnData(start, nb, entity.FieldTypeInt8, "int8"),
		common.GenColumnData(start, nb, entity.FieldTypeInt16, "int16"),
		common.GenColumnData(start, nb, entity.FieldTypeInt32, "int32"),
		common.GenColumnData(start, nb, entity.FieldTypeFloat, "float"),
		common.GenColumnData(start, nb, entity.FieldTypeDouble, "double"),
		common.GenColumnData(start, nb, entity.FieldTypeVarChar, "varchar"),
		common.GenDefaultJSONData("json", start, nb),
	}
	data = append(data, common.GenAllArrayData(start, nb, common.WithArrayCapacity(capacity))...)

	queryResultAll, errQuery := mc.Query(ctx, collName, []string{},
		fmt.Sprintf("%s == 0", common.DefaultIntFieldName), []string{"int64", "float"})
	common.CheckErr(t, errQuery, true)
	common.CheckQueryResult(t, queryResultAll, data)
	allFieldsName := []string{
		"int64", "bool", "int8", "int16", "int32", "float", "double", "varchar", "json", "floatVector",
	}
	common.CheckOutputFields(t, queryResultAll, append(allFieldsName, common.AllArrayFieldsName...))
}
```

**Comment by congqixia** [comment]
/assign @ThreadDao 
could you please verify the fix? thanks in advance

**Comment by ThreadDao** [comment]
@congqixia 
Verified, fixed.
Could you add ElementType for column, So I can get the array column data like this:
arrayColumn.(*entity.ColumnBinaryVector).Data()
Now I can only know arrayColumn FieldType array and get FieldData

**Comment by ThreadDao** [comment]
Fixed
