### ISSUE TITLE
[Bug]:  panic: runtime error: slice bounds out of range when inserting sparse embeeding with high dimension

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus-sdk-go#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- go-sdk: master
case:
```
// the dimension of a sparse embedding can be any value from 0 to (maximum of uint32 - 1)
func TestInsertSparseDataMaxDim(t *testing.T) {
	// invalid sparse vector: positions >= uint32
	ctx := createContext(t, time.Second*common.DefaultTimeout)
	// connect
	mc := createMilvusClient(ctx, t)

	cp := CollectionParams{CollectionFieldsType: Int64VarcharSparseVec, AutoID: false, EnableDynamicField: true,
		ShardsNum: common.DefaultShards, Dim: common.DefaultDim, MaxLength: common.TestMaxLen}
	collName := createCollection(ctx, t, mc, cp)

	// insert data column
	data := []entity.Column{
		common.GenColumnData(0, 1, entity.FieldTypeInt64, common.DefaultIntFieldName),
		common.GenColumnData(0, 1, entity.FieldTypeVarChar, common.DefaultVarcharFieldName),
		common.GenColumnData(0, 1, entity.FieldTypeFloatVector, common.DefaultFloatVecFieldName, common.WithVectorDim(common.DefaultDim)),
	}
	// sparse vector with max dim
	positions := []uint32{0, math.MaxUint32 - 10, math.MaxUint32 - 1}
	values := []float32{0.453, 5.0776, 100.098}
	sparseVec, err := entity.NewSliceSparseEmbedding(positions, values)
	common.CheckErr(t, err, true)
	data = append(data, entity.NewColumnSparseVectors(common.DefaultSparseVecFieldName, []entity.SparseEmbedding{sparseVec}))
	_, err = mc.Insert(ctx, collName, "", data...)
	common.CheckErr(t, err, false)
}
```
result:
```
2024/04/10 18:06:49 milvus_client.go:14: (ApiRequest): func [Insert], args: [context.Background.WithDeadline(2024-04-10 18:08:49.450372908 +0800 CST m=+120.004360407 [1m59.908289726s]) gRxo  [0xc000400270 0xc0004002a0 0xc0004002d0 0xc000400330]]
2024/04/10 18:06:49 milvus_client.go:14: (ApiRequest): func [DropCollection], args: [context.Background.WithDeadline(2024-04-10 18:08:49.450372908 +0800 CST m=+120.004360407 [1m59.886343074s]) gRxo]
2024/04/10 18:06:49 milvus_client.go:21: (ApiResponse): func [DropCollection], results: []
2024/04/10 18:06:49 milvus_client.go:14: (ApiRequest): func [Close], args: []
2024/04/10 18:06:49 milvus_client.go:21: (ApiResponse): func [Close], results: []
--- FAIL: TestInsertSparseDataMaxDim (0.14s)
panic: runtime error: slice bounds out of range [4294967212:24] [recovered]
	panic: runtime error: slice bounds out of range [4294967212:24]

goroutine 6 [running]:
testing.tRunner.func1.2({0xb88780, 0xc0004b4030})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0xb88780, 0xc0004b4030})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/milvus-io/milvus-sdk-go/v2/entity.(*ColumnSparseFloatVector).FieldData(0xc000400330)
	/home/zong/zong/go-projects/milvus-sdk-go/entity/columns_sparse.go:176 +0x457
github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).processInsertColumns(0xc0000888c0?, 0xc000418730, {0xc000410120, 0x4, 0x4?})
	/home/zong/zong/go-projects/milvus-sdk-go/client/insert.go:147 +0xadb
github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).Insert(0xc0000888c0, {0xcf7190, 0xc000046ba0}, {0xc000369460, 0x4}, {0x0, 0x0}, {0xc000410120, 0x4, 0x6})
	/home/zong/zong/go-projects/milvus-sdk-go/client/insert.go:56 +0x132
github.com/milvus-io/milvus-sdk-go/v2/test/base.(*MilvusClient).Insert(0xc00039c370, {0xcf7190?, 0xc000046ba0}, {0xc000369460, 0x4}, {0x0, 0x0}, {0xc000410120, 0x4, 0x6})
	/home/zong/zong/go-projects/milvus-sdk-go/test/base/milvus_client.go:364 +0x25c
github.com/milvus-io/milvus-sdk-go/v2/test/testcases.TestInsertSparseDataMaxDim(0x0?)
	/home/zong/zong/go-projects/milvus-sdk-go/test/testcases/insert_test.go:589 +0x46c
testing.tRunner(0xc00036c9c0, 0xc38650)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f

```

**Comment by congqixia** [comment]
patch merged, could please verify?
/unassign
/assign @ThreadDao

**Comment by ThreadDao** [comment]
fixed
