### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference when search with invalid sparse params

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus-sdk-go#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image: master-20240415-fd971a43-amd64
sdk: go-branch

search with invalid sparse params:
```
	for _, dropRatio := range []float64{1.2, -0.3} {
		sp, _ := entity.NewIndexSparseInvertedSearchParam(dropRatio)
		_, errSearch := mc.Search(ctx, collName, []string{}, "", []string{"*"}, queryVec, common.DefaultSparseVecFieldName,
			entity.IP, common.DefaultTopK, sp)
		common.CheckErr(t, errSearch, false, "invalid")
	}
```
panic:
```
2024/04/16 21:01:00 milvus_client.go:14: (ApiRequest): func [Search], args: [context.Background.WithDeadline(2024-04-16 21:04:50.136658098 +0800 CST m=+240.004062478 [3m49.215780544s]) pRTB []  [*] nq=5 sparseVec IP 10 <nil> []]
2024/04/16 21:01:00 milvus_client.go:14: (ApiRequest): func [DropCollection], args: [context.Background.WithDeadline(2024-04-16 21:04:50.136658098 +0800 CST m=+240.004062478 [3m49.215752788s]) pRTB]
2024/04/16 21:01:00 milvus_client.go:21: (ApiResponse): func [DropCollection], results: []
2024/04/16 21:01:00 milvus_client.go:14: (ApiRequest): func [Close], args: []
2024/04/16 21:01:00 milvus_client.go:21: (ApiResponse): func [Close], results: []
--- FAIL: TestSearchSparseVectorInvalidParms (10.80s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9f4880]

goroutine 6 [running]:
testing.tRunner.func1.2({0xb28880, 0x11d75c0})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0xb28880, 0x11d75c0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/milvus-io/milvus-sdk-go/v2/entity.(*IndexSparseInvertedSearchParam).Params(0xc000b097f0?)
	<autogenerated>:1
github.com/milvus-io/milvus-sdk-go/v2/client.prepareSearchRequest({0xc000114048, 0x4}, {0x12234d0, 0x0, 0x0}, {0x0, 0x0}, {0xc00040c860, 0x1, 0x1}, ...)
	/home/zong/zong/go-projects/milvus-sdk-go/client/data.go:395 +0x87
github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).Search(0xc0000888c0, {0xd1fc70, 0xc000046ba0}, {0xc000114048, 0x4}, {0x12234d0, 0x0, 0x0}, {0x0, 0x0}, ...)
	/home/zong/zong/go-projects/milvus-sdk-go/client/data.go:115 +0x210
github.com/milvus-io/milvus-sdk-go/v2/test/base.(*MilvusClient).Search(0xc000542110, {0xd1fc70?, 0xc000046ba0}, {0xc000114048, 0x4}, {0x12234d0, 0x0, 0x0}, {0x0, 0x0}, ...)
	/home/zong/zong/go-projects/milvus-sdk-go/test/base/milvus_client.go:407 +0x5a3
github.com/milvus-io/milvus-sdk-go/v2/test/testcases.TestSearchSparseVectorInvalidParms(0x0?)
	/home/zong/zong/go-projects/milvus-sdk-go/test/testcases/search_test.go:1658 +0x619
testing.tRunner(0xc000378680, 0xc5cd48)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

### Steps To Reproduce

```markdown
func TestSearchSparseVectorInvalidParams(t *testing.T) {
	ctx := createContext(t, time.Second*common.DefaultTimeout*2)
	// connect
	mc := createMilvusClient(ctx, t)

	// create -> insert [0, 3000) -> flush -> index -> load
	cp := CollectionParams{CollectionFieldsType: Int64VarcharSparseVec, AutoID: false, EnableDynamicField: true,
		ShardsNum: common.DefaultShards, Dim: common.DefaultDim, MaxLength: common.TestMaxLen}

	dp := DataParams{DoInsert: true, CollectionFieldsType: Int64VarcharSparseVec, start: 0, nb: common.DefaultNb * 2,
		dim: common.DefaultDim, EnableDynamicField: true}

	// index params
	idxHnsw, _ := entity.NewIndexHNSW(entity.L2, 8, 96)
	idxWand := entity.NewGenericIndex(common.DefaultSparseVecFieldName, "SPARSE_WAND", map[string]string{"drop_ratio_build": "0.3", "metric_type": "IP"})
	ips := []IndexParams{
		{BuildIndex: true, Index: idxWand, FieldName: common.DefaultSparseVecFieldName, async: false},
		{BuildIndex: true, Index: idxHnsw, FieldName: common.DefaultFloatVecFieldName, async: false},
	}
	collName := prepareCollection(ctx, t, mc, cp, WithDataParams(dp), WithIndexParams(ips), WithCreateOption(client.WithConsistencyLevel(entity.ClStrong)))

	// range search
	queryVec := common.GenSearchVectors(common.DefaultNq, common.DefaultDim, entity.FieldTypeSparseVector)

	for _, dropRatio := range []float64{1.2, -0.3} {
		sp, _ := entity.NewIndexSparseInvertedSearchParam(dropRatio)
		_, errSearch := mc.Search(ctx, collName, []string{}, "", []string{"*"}, queryVec, common.DefaultSparseVecFieldName,
			entity.IP, common.DefaultTopK, sp)
		common.CheckErr(t, errSearch, false, "invalid")
	}
}
```
```


### Environment

_No response_

### Anything else?

_No response_

**Comment by congqixia** [comment]
```
sp, _ := entity.NewIndexSparseInvertedSearchParam(dropRatio)
```
this test scripts ignored error check. when dropRatio is not valid, an error will be returned

/unassign
/assign @ThreadDao

**Comment by ThreadDao** [comment]
@congqixia sorry. I will fix the case
